#! /bin/bash

COLUMNSX="4 5 7 9 10"
COLUMNSY="4 5 7 9 10"

rm *.svg

for X in $COLUMNSX
do
	for Y in $COLUMNSY
	do
		WX=$(($X - 1))
		WY=$(($Y - 1))
		TITLE="W$WX × W$WY"
		gnuplot -e "col1 = $X" -e "col2 = $Y" -e "maintitle = '$TITLE'" plot > $WX-$WY.svg
	done
done
		
